SET
  UNIQUE_CHECKS = 0;

SET
  FOREIGN_KEY_CHECKS = 0;

CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8;

USE `library`;

DROP TABLE IF EXISTS `library`.`member`;

CREATE TABLE IF NOT EXISTS `library`.`member` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NULL DEFAULT NULL,
  `PHONE_NUMBER` VARCHAR(15) NULL,
  `AUTH_CARD_NUMBER` CHAR(8) NULL,
  `ADDRESS` VARCHAR(255) NULL,
  `DELETED` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARACTER SET = utf8;

DROP TABLE IF EXISTS `library`.`media`;

CREATE TABLE IF NOT EXISTS `library`.`media` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(255) NULL,
  `AUTHOR` VARCHAR(255) NULL,
  `TYPE` VARCHAR(255) NULL,
  `SOURCE_DATE` DATE NULL,
  `STATUS` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

DROP TABLE IF EXISTS `library`.`rent`;

CREATE TABLE IF NOT EXISTS `library`.`rent` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `MEDIA_ID` INT NOT NULL,
  `MEMBER_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`MEDIA_ID`) REFERENCES `library`.`media`(`ID`),
  FOREIGN KEY (`MEMBER_ID`) REFERENCES `library`.`member`(`ID`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

SET
  UNIQUE_CHECKS = 1;

SET
  FOREIGN_KEY_CHECKS = 1;